Forum/Web/ViewModels/PostSummaryViewModel.cs
using Service.DtoModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Web.ViewModels
{
    public class PostSummaryViewModel : BaseViewModel<PostDTO>
    {

        public int CommentCount { get; set; }
        public int LikeCount { get; set; }
        public string Title { get; set; }
        public int Id { get; set; }
        
        public EntryViewModel Entry { get; set; }

        public PostSummaryViewModel() : base() { }
        public PostSummaryViewModel(PostDTO dto) : base(dto) { }

        public override PostDTO ToDTO()
        {
            PostDTO dto = new PostDTO()
            {
                Title = this.Title,
                Entry = new EntryDTO()
                {
                    Content = this.Entry.Content
                }
            };

            return dto;
        }

        protected override void FromDTO(PostDTO data)
        {

            this.Entry = new EntryViewModel(data.Entry);
            
            CommentCount = data.Comments.Count;
            LikeCount = data.Entry.Likes.Count;
            Title = data.Title;
            Id = data.Id;
        }
    }
}

Forum/Web/Controllers/AuthController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Service.Contracts;
using Service.DtoModels;
using Service.Enums;
using Service.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Web.ViewModels;

namespace Web.Controllers
{
    public class AuthController : Controller
    {

        const string USER_ID = "UserId";
        const string ADMINISTRATOR = "Administrator";
        const string USER_NAME = "CurrentUser";

        static UserViewModel _currentUser;
        public static UserViewModel CurrentUser
        {
            get{
                return _currentUser;
            }
        }

        private readonly IUserService userService;
        public AuthController(IUserService userService)
        {
            this.userService = userService;
        }
        public IActionResult Login()
        {
            if(this.HttpContext.Session.GetString("CurrentUser") != null)
            {
                return RedirectToAction("Index", "Posts");
            }

            var loginViewModel = new LoginViewModel();

            return this.View(loginViewModel);
        }

        [HttpPost]
        public IActionResult Login([Bind("Username, Password")] LoginViewModel loginViewModel)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(loginViewModel);
            }

            try
            {
                var user = this.userService.AuthenticateUser(loginViewModel.Username, loginViewModel.Password);
                if (user == null)
                {
                    throw new NullReferenceException("Invalid credentials.");
                }

                _currentUser = new UserViewModel(user);

                switch (user.UserPrivilege.Privilege)
                {
                    case UserPrivilegeLevel.Admin:
                        this.HttpContext.Session.SetInt32("Administrator", 1);
                        this.HttpContext.Session.SetInt32("UserId", user.Id);
                        break;

                    case UserPrivilegeLevel.User:
                        this.HttpContext.Session.SetInt32("UserId", user.Id);
                        break;

                    case UserPrivilegeLevel.Blocked:
                        this.HttpContext.Session.SetInt32("UserId", user.Id);
                        break;
                }

                this.HttpContext.Session.SetString("CurrentUser", user.Username);

                return RedirectToAction("Index", "Posts");

            }
            catch (ArgumentException)
            {
                TempData["error"] = "Invalid login credentials.";
                return RedirectToAction("Login", loginViewModel);
            }
        }

        public IActionResult Logout()
        {
            this.HttpContext.Session.Remove("CurrentUser");
            this.HttpContext.Session.Remove("Administrator");
            this.HttpContext.Session.Remove("UserId");
            _currentUser = null;

            return this.RedirectToAction("index", "home");
        }

        public IActionResult Register()
        {
            var registerViewModel = new RegisterViewModel();

            return this.View(registerViewModel);
        }

        [HttpPost]
        public IActionResult Register([Bind("Username, DisplayName, Email, Password, ConfirmPassword")] RegisterViewModel registerViewModel)
        {

            if (!this.ModelState.IsValid)
            {
                TempData["error"] = "Please fill all fields.";
                return RedirectToAction("Register", registerViewModel);
            }

            if (!EmailValidator.EmailIsValid(registerViewModel.Email))
            {
                TempData["error"] = "Invalid email.";
                return RedirectToAction("Register", registerViewModel);
            }

            if (!PasswordValidator.IsValidPassword(registerViewModel.Password))
            {
                TempData["error"] = "Password must be at least 8 symbols and should contain capital letter, digit and special symbol.";
                return RedirectToAction("Register", registerViewModel);
            }

            try
            {
                this.userService.CheckForAvailability(registerViewModel.Username, registerViewModel.Email, registerViewModel.DisplayName);
            }
            catch (ArgumentException e)
            {
                if (e.Message.Equals("Username already taken."))
                {
                    this.ModelState.AddModelError("Username", "Username already taken.");
                    return this.View(registerViewModel);
                }
                if (e.Message.Equals("Display name already taken."))
                {
                    this.ModelState.AddModelError("DisplayName", "Display name already taken.");
                    return this.View(registerViewModel);
                }
                if (e.Message.Equals("Email already taken."))
                {
                    this.ModelState.AddModelError("Email", "Email already taken.");
                    return this.View(registerViewModel);
                }
            }
            
            this.userService.Create(new UserDTO()
            {
                DisplayName = registerViewModel.DisplayName,
                Email = registerViewModel.Email,
                Password = PasswordValidator.HashPassword(registerViewModel.Password),
                Username = registerViewModel.Username,
                UserPrivilege = new UserPrivilegeDTO()
                {
                    Privilege = UserPrivilegeLevel.User
                },
                ProfilePicture = "~/Images/default_picture.png"
            });
            return this.RedirectToAction(nameof(this.Login));
        }

    }
}

Forum/Web/Views/Shared/PostSummary.cshtml
@using Microsoft.AspNetCore.Http;
@{
    this.ViewData["IsAuthenticated"] = this.Context.Session.Keys.Contains("CurrentUser");
    this.ViewData["CurrentUser"] = this.Context.Session.GetString("CurrentUser");
    this.ViewData["CurrentUserObj"] = Web.Controllers.AuthController.CurrentUser;
}

@model Web.ViewModels.PostSummaryViewModel

@{
    var user = (Web.ViewModels.UserViewModel)this.ViewData["CurrentUserObj"];
}

<div class="container">
    <div class="row">
        <!--style="border-width:thin; border:solid"-->
        <div class="col-md-2">
            @Html.Partial("UserProfileHeader", Model.Entry.Author)
        </div>
        <div class="col-md-8">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h3 class="panel-title">

                        @if (user == null)
                        {
                            @Html.ActionLink(Model.Title, "Index", "Home", new { register = true })
                        }
                        else
                        {
                            @Html.ActionLink(Model.Title, "Details", "Posts", new { id = Model.Id })
                        }
                        <br />
                        <!--Html.DisplayFor(modelItem => Model.Title)-->
                        <span class="pull-right">
                            <span class="glyphicon glyphicon-heart" aria-hidden="true">
                            </span>
                            @Html.DisplayFor(modelItem => Model.LikeCount)
                            <span class="glyphicon glyphicon-comment" aria-hidden="true">
                            </span>
                            @Html.DisplayFor(modelItem => Model.CommentCount)
                        </span>
                        <br />
                    </h3>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-8">

                        </div>
                        <div class="col-md-4">
                            <i>
                                Posted at: @Html.DisplayFor(modelItem => Model.Entry.CreationTime)

                                @{
                                    @if ((Model.Entry.EditTime - Model.Entry.CreationTime).TotalSeconds > 1000f)
                                    {

                                        @Html.Raw("Edited at: ")
                                        @Html.DisplayFor(modelItem => Model.Entry.EditTime)

                                      }

                                  }
                                    </i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-2">
            @{
                if (user != null)
                {
                    if (user.Privilege.PrivilegeLevel == Service.Enums.UserPrivilegeLevel.Admin || Model.Entry.Author.Id == user.Id)
                    {
                        <button type="button" class="btn btn-danger" onclick="location.href='@Url.Action("DeletePost", "Posts", new { id = Model.Id })'">
                            <span class="glyphicon glyphicon-remove" aria-hidden="true">
                            </span>
                        </button>
                    }
                }
            }
        </div>
    </div>
</div>
<br />

Forum/Web/Views/Shared/UserProfileHeader.cshtml
@model Web.ViewModels.UserViewModel
<div style="text-align: center">
    <img src="@Url.Content($"{Model.ProfilePicture}")" alt="" height=100 width=100 class="img-circle" />
    @*<span class="glyphicon glyphicon glyphicon-user" aria-hidden="true">
        </span>*@
    <br />
    <br />
    @Html.DisplayFor(modelItem => Model.DisplayName)
    <br />
    <span class="
glyphicon glyphicon-envelope" aria-hidden="true">
    </span> @Model.PostCount
    <span class="glyphicon glyphicon-heart" aria-hidden="true">
    </span>
    @Model.LikeCount
    <span class="glyphicon glyphicon-comment" aria-hidden="true">
    </span> @Model.CommentCount

</div>

Forum/Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;
@{
    this.ViewData["IsAuthenticated"] = this.Context.Session.Keys.Contains("CurrentUser");
    this.ViewData["CurrentUser"] = this.Context.Session.GetString("CurrentUser");
    this.ViewData["CurrentUserObj"] = Web.Controllers.AuthController.CurrentUser;
}

@{
    var user = (Web.ViewModels.UserViewModel)this.ViewData["CurrentUserObj"];
}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>Forum @ViewData["Title"]</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
</head>

<body style="background-color: #f5f3f0; ">
    
    <header>
        @{

            if (user != null)
            {

                <nav class="navbar navbar-default">
                    <div class="container-fluid" style="justify-content: center; text-align: center;">

                        <!-- This will link to Posts index-->
                        <p class="navbar-text navbar-left"> <a href='@Url.Action("Index", "Posts")' class="navbar-link"><img src="~/Images/Logo.png" height=50 width=50 alt="" class="img-fluid" /><br />Listen Up!</a></p>

                        <p class="navbar-text navbar-right"><a href='@Url.Action("Details", "Users",new {id=user.Id})' class="navbar-link"><img src="@Url.Content($"{user.ProfilePicture}")" height=50 width=50 alt="" class="img-fluid" /><br />Signed in as @user.DisplayName </a></p>

                        <p class="navbar-text navbar-right"> <a href='@Url.Action("Index", "Users",new {id=user.Id})' class="navbar-link"><span class="glyphicon glyphicon-user" aria-hidden="true" style="font-size: 46px"></span><br />Community</a></p>

                    </div>
                </nav>
            }
        }


        <!--
        <nav class="navbar navbar-default">
            <div class="container-fluid">
            <div class="navbar-header">

                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">Forum</a>
            </div>

            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a asp-controller="Posts" asp-action="Index">Posts</a></li>
                    <li><a asp-controller="Users" asp-action="Index">Users</a></li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    <li><a href="#">Link</a></li>
                    <li class="dropdown">
                        @if (this.ViewData["CurrentUser"] != null)
                        {
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Logged as @this.ViewData["CurrentUser"] <span class="caret"></span></a>
                        }
                        else
                        {
                            <a asp-controller="Auth" asp-action="Login">Log in</a>
                        }
                        <ul class="dropdown-menu">

                            @*<li role="separator" class="divider"></li>*@
                            <li><a asp-controller="Settings" asp-action="Index">Change profile picture</a></li>
                            <li><a asp-controller="Auth" asp-action="Logout">Log out</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
            </div>
            </nav>
                -->
    </header>

    <div class="body-content">
        @RenderBody()
    </div>

    @*<footer>
            <p>footer</p>
        </footer>*@

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="sha384-nvAa0+6Qg9clwYCGGPpDQLVpLNn0fRaROjHqs13t4Ggj3Ez50XnGQqc/r8MhnRDZ" crossorigin="anonymous"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>
</body>
</html>