Forum/Web/ViewModels/CommentViewModel.cs
using Service.DtoModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Web.ViewModels
{
    public class CommentViewModel : BaseViewModel<CommentDTO>
    {

        public EntryViewModel Entry { get; set; }
        public int Id { get; set; }

        public int PostId { get; set; }

        public CommentViewModel() : base() { }
        public CommentViewModel(CommentDTO dto) : base(dto) { }

        public override CommentDTO ToDTO()
        {
            return new CommentDTO
            {
                Entry = this.Entry.ToDTO(),
                Id = this.Id,
                PostId = this.PostId
            };
        }

        protected override void FromDTO(CommentDTO data)
        {
            Entry = new EntryViewModel(data.Entry);
            Id = data.Id;
            PostId = data.PostId;
        }
    }
}

Forum/Web/Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Service.Contracts;
using Web.ViewModels;
using Service.DtoModels;
using Service.Enums;

namespace Web.Controllers
{
    public class PostsController : BaseController
    {
        private readonly IPostService service;
        private readonly ILikeService likeService;
        private readonly IEntryService entryService;
        private readonly ICommentService commentService;

        public PostsController(IPostService service, ILikeService likeService, IEntryService entryService, ICommentService commentService, IUserService userService) : base(userService)
        {
            this.service = service;
            this.likeService = likeService;
            this.entryService = entryService;
            this.commentService = commentService;
        }

        // GET: Posts
        public IActionResult Index(int pg = 1, PostSortStrategy sortStrategy = PostSortStrategy.None, PostFilterStrategy filterStrategy =PostFilterStrategy.None, string filterData = null)
        {
            if (this.GetLoggedInUser() == null)
            {
                return RedirectToAction("Login", "Auth");
            }

            if (filterData == null)
            {
                filterStrategy = PostFilterStrategy.None;
            }


            var data = service.GetAll(sortStrategy,filterStrategy,filterData);

            foreach (PostDTO dto in data)
            {
                this.userService.PopulateUserDTO(dto.Entry.Author);
            }

            const int pageSize = 4;
            if (pg < 1)
            {
                pg = 1;
            }
            int recsCount = data.Count();
            var pager = new Pager(recsCount, pg, pageSize);
            int recSkip = (pg - 1) * pageSize;
            var dataForPage = data.Skip(recSkip).Take(pager.PageSize).ToList();
            PostSummaryListViewModel listView = new PostSummaryListViewModel(dataForPage);

            this.ViewBag.Pager = pager;

            ViewData.Add("SortStrategy", sortStrategy);
            ViewData.Add("FilterStrategy", filterStrategy);
            ViewData.Add("FilterData", filterData);

            return View(listView);

        }

        // GET: Posts/Details/5
        public IActionResult Details(int? id, CommentSortStrategy sortStrategy = CommentSortStrategy.None)
        {
            if (id == null)
            {
                return NotFound();
            }

            PostDTO p = service.Get(id.Value);
            p.ApplySortingToComments(sortStrategy);

            if (p == null)
            {
                return NotFound();
            }

            userService.PopulateUserDTO(p.Entry.Author);

            for(int i = 0; i < p.Comments.Count; i++)
            {
                userService.PopulateUserDTO(p.Comments[i].Entry.Author);
            }

            //Create a details view...

            ViewData.Add("SortStrategy", sortStrategy);  

            PostDetailsViewModel view = new PostDetailsViewModel(p);

            return View(view);
        }

        public IActionResult RemoveLike(int? id, int? postId, int? userId)
        {
            /*EntryDTO p = entryService.Get(id.Value);

            if (p == null)
            {
                return NotFound();
            }*/

            UserDTO user = GetLoggedInUser();

            likeService.Delete(id.Value);

            int pId = postId.Value;

            return this.RedirectToAction("details", "posts", new { id = pId });
        }

        public IActionResult LikePost(int? id, int? postId)
        {

            EntryDTO p = entryService.Get(id.Value);

            if (p == null)
            {
                return NotFound();
            }

            UserDTO user = GetLoggedInUser();

            LikeDTO like = new LikeDTO
            {
                AuthorId = user.Id,
                EntryId = p.Id
            };

            likeService.Create(like);

            int pId = postId.Value;

            return this.RedirectToAction("details", "posts", new { id = pId });

        }

        public IActionResult LikeComment(int? id, int? postId)
        {

            EntryDTO p = entryService.Get(id.Value);

            if (p == null)
            {
                return NotFound();
            }

            UserDTO user = GetLoggedInUser();

            LikeDTO like = new LikeDTO
            {
                AuthorId = user.Id,
                EntryId = p.Id
            };

            likeService.Create(like);

            return this.RedirectToAction("details", "posts", new { id = postId.Value });

        }

        [HttpPost]
        public IActionResult AddComment(int id, string content)
        {

            PostDTO p = service.Get(id);

            if (p == null)
            {
                return NotFound();
            }

            UserDTO user = GetLoggedInUser();

            CommentDTO comment = new CommentDTO
            {
                PostId = p.Id,
                Entry = new EntryDTO
                {
                    AuthorId = user.Id,
                    Content = content
                }

            };

            commentService.Create(comment);

            int postId = id;

            return this.RedirectToAction("details", "posts", new { id = postId });

        }

        [HttpPost]
        public IActionResult EditComment(int id, string content)
        {

            UserDTO user = GetLoggedInUser();

            //Do some sort of security here I guess

            CommentDTO comment = commentService.Get(id);

            if(comment == null)
            {
                return NotFound();
            }

            comment.Entry.Content = content;

            commentService.Update(comment.Id, comment);

            int postId = comment.PostId;

            return this.RedirectToAction("details", "posts", new { id = postId });

        }

        [HttpPost]
        public IActionResult EditPost(int id, string title, string content)
        {

            UserDTO user = GetLoggedInUser();

            //Do some sort of security here I guess

            PostDTO post = service.Get(id);

            if (post == null)
            {
                return NotFound();
            }

            post.Title = title;
            post.Entry.Content = content;

            service.Update(post.Id, post);

            int postId = post.Id;

            return this.RedirectToAction("details", "posts", new { id = postId });

        }

        public IActionResult DeletePost(int id)
        {

            UserDTO user = GetLoggedInUser();

            //Do some sort of security here I guess

            PostDTO post = service.Get(id);

            if (post == null)
            {
                return NotFound();
            }

            service.Delete(post.Id);

            return this.RedirectToAction("index", "posts");

        }

        public IActionResult DeleteComment(int id)
        {

            UserDTO user = GetLoggedInUser();

            //Do some sort of security here I guess

            CommentDTO comment = commentService.Get(id);

            if (comment == null)
            {
                return NotFound();
            }

            int postId = comment.PostId;

            commentService.Delete(comment.Id);

            return this.RedirectToAction("details", "posts", new { id = postId });

        }

        [HttpPost]
        public IActionResult CreatePost(string title, string content)
        {

            UserDTO user = GetLoggedInUser();

            PostDTO post = new PostDTO
            {
                Title = title,
                Entry = new EntryDTO
                {
                    AuthorId = user.Id,
                    Content = content
                }

            };

            PostDTO created = this.service.Create(post);

            int postId = created.Id;

            return this.RedirectToAction("details", "posts", new { id = postId });

        }

        /*
        // GET: Posts/Create
        public IActionResult Create()
        {
            ViewData["EntryId"] = new SelectList(_context.Entries, "Id", "Id");
            return View();
        }

        // POST: Posts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Title,EntryId,Id,IsDeleted")] Post post)
        {
            if (ModelState.IsValid)
            {
                _context.Add(post);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["EntryId"] = new SelectList(_context.Entries, "Id", "Id", post.EntryId);
            return View(post);
        }

        // GET: Posts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Posts.FindAsync(id);
            if (post == null)
            {
                return NotFound();
            }
            ViewData["EntryId"] = new SelectList(_context.Entries, "Id", "Id", post.EntryId);
            return View(post);
        }

        // POST: Posts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Title,EntryId,Id,IsDeleted")] Post post)
        {
            if (id != post.Id)
            {

Forum/Web/Views/Posts/Comment.cshtml
@using Microsoft.AspNetCore.Http;
@{
    this.ViewData["IsAuthenticated"] = this.Context.Session.Keys.Contains("CurrentUser");
    this.ViewData["CurrentUser"] = this.Context.Session.GetString("CurrentUser");
    this.ViewData["CurrentUserObj"] = Web.Controllers.AuthController.CurrentUser;
}
@model Web.ViewModels.CommentViewModel
@{
    var user = (Web.ViewModels.UserViewModel)this.ViewData["CurrentUserObj"];
}
<div class="container">
    <div class="row">
        <div class="col-md-2">
            @Html.Partial("UserProfileHeader", Model.Entry.Author)
        </div>
        <div class="col-md-8">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-md-8">

                        </div>
                        <div class="col-md-4">
                            <i>
                                Posted at: @Html.DisplayFor(modelItem => Model.Entry.CreationTime)
                            </i>
                        </div>
                    </div>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-12">
                            @Html.DisplayFor(modelItem => Model.Entry.Content)
                        </div>
                    </div>
                    <br />
                    <div class="row">
                        <div class="col-md-10">
                        </div>
                        <div class="col-md-2">
                            <span class="pull-right">

                                @{

                                    var like = Model.Entry.Likes.FirstOrDefault(x => x.Author.Id == user.Id);

                                    if (like != null)
                                    {

                                        <button type="button" class="btn btn-danger" onclick="location.href='@Url.Action("RemoveLike", "Posts", new { id = like.Id, postId = Model.PostId, userId = user.Id })'">
                                            <span class="glyphicon glyphicon-heart" aria-hidden="true">
                                            </span>
                                            @Html.DisplayFor(modelItem => Model.Entry.Likes.Count)
                                        </button>
                                    }
                                    else
                                    {

                                        <button type="button" class="btn btn-info" onclick="location.href='@Url.Action("LikeComment", "Posts", new { id = Model.Entry.Id, postId = Model.PostId })'">
                                            <span class="glyphicon glyphicon-heart" aria-hidden="true">
                                            </span>
                                            @Html.DisplayFor(modelItem => Model.Entry.Likes.Count)
                                        </button>
                                    }
                                }

                            </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    @{
                        if (user.Privilege.PrivilegeLevel == Service.Enums.UserPrivilegeLevel.Admin || Model.Entry.Author.Id == user.Id)
                        {
                            <span class="pull-right">
                                <button type="button" class="btn btn-info"
                                        data-toggle="collapse" data-target="#editCommentPanel" aria-expanded="false" aria-controls="editCommentPanel">
                                    <span class="glyphicon glyphicon-pencil" aria-hidden="true">
                                    </span>
                                </button>
                                <button type="button" class="btn btn-danger" onclick="location.href='@Url.Action("DeleteComment", "Posts", new { id = Model.Id })'">
                                    <span class="glyphicon glyphicon-remove" aria-hidden="true">
                                    </span>
                                </button>
                            </span>
                        }
                    }
                </div>
            </div>
        </div>
        <div class="col-md-2">
        </div>
    </div>
</div>
<br />
<div class="collapse" id="editCommentPanel">
    <div class="container">
        <div class="row">
            <div class="col-md-2">
            </div>
            <div class="col-md-8" div style="text-align:center">
                <!-- Put the thing here -->
                <form method="post" enctype="multipart/form-data" asp-controller="Posts" asp-action="EditComment">
                    <input type="hidden" name="id" id="id" value=@Model.Id>
                    <div class="row">
                        <div class="form-horizontal">
                            <div class="form-group">
                                <div class="col-md-12">
                                    <textarea id="content" name="content" class="form-control" rows="9" style="resize: none;" placeholder=@Model.Entry.Content required>@Model.Entry.Content</textarea>
                                </div>
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-info">
                        <span class="glyphicon glyphicon-pencil" aria-hidden="true">
                        </span>
                        Save...
                    </button>
                </form>
                <!-- and then put a centered button here-->
            </div>
            <div class="col-md-2">
            </div>
        </div>
    </div>
</div>
<br />

Forum/Web/Views/Posts/Create.cshtml
@model Data.Models.Post

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Post</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EntryId" class="control-label"></label>
                <select asp-for="EntryId" class ="form-control" asp-items="ViewBag.EntryId"></select>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsDeleted" /> @Html.DisplayNameFor(model => model.IsDeleted)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Forum/Web/Views/Posts/Delete.cshtml
@model Data.Models.Post

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Post</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Entry)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Entry.Id)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsDeleted)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsDeleted)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Forum/Web/Views/Posts/Index.cshtml
@using Microsoft.AspNetCore.Http;
@using Web.ViewModels
@{
    this.ViewData["IsAuthenticated"] = this.Context.Session.Keys.Contains("CurrentUser");
    this.ViewData["CurrentUser"] = this.Context.Session.GetString("CurrentUser");
    this.ViewData["CurrentUserObj"] = Web.Controllers.AuthController.CurrentUser;
    Pager pager = new Pager();
    int pageNo = 0;
    if (this.ViewBag.Pager != null)
    {
        pager = ViewBag.Pager;
        pageNo = pager.CurrentPage;
    }
}

@model Web.ViewModels.PostSummaryListViewModel
<!--<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
-->
@{
    var user = (Web.ViewModels.UserViewModel)this.ViewData["CurrentUserObj"];
}

<div class="container">
    <div class="row">
        <div class="col-md-2">
        </div>
        <div class="col-md-8">
            @{
                if (user.Privilege.PrivilegeLevel != Service.Enums.UserPrivilegeLevel.Blocked)
                {
                    <span class="pull-right">
                        <button type="button" class="btn btn-info"
                                data-toggle="collapse" data-target="#createPanel" aria-expanded="true" aria-controls="createPanel">
                            New Post
                            <span class="glyphicon glyphicon-plus" aria-hidden="true">
                            </span>
                        </button>
                    </span>
                }
            }
        </div>
        <div class="col-md-2">

        </div>
    </div>
</div>

<br />

<div class="collapse" id="createPanel">
    <div class="container">
        <div class="row">
            <div class="col-md-2">
                <!--Put current author face here-->
            </div>
            <div class="col-md-8">
                <form method="post" enctype="multipart/form-data" asp-controller="Posts" asp-action="CreatePost">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <input type="text" id="title" name="title" class="form-control" placeholder="Title">
                        </div>
                        <div class="panel-body" style="text-align:center">
                            <br />
                            <textarea id="content" name="content" class="form-control" rows="9" style="resize: none;" placeholder="What's up?" required></textarea>
                            <br />
                            <button type="submit" class="btn btn-info">
                                New Post
                                <span class="glyphicon glyphicon-plus" aria-hidden="true">
                                </span>
                            </button>
                        </div>
                    </div>
                </form>


            </div>
            <div class="col-md-2">

            </div>
        </div>
    </div>
</div>

<br />

@{

    string[] sortValues = Enum.GetNames(typeof(Service.Enums.PostSortStrategy));
    string[] filterValues = Enum.GetNames(typeof(Service.Enums.PostFilterStrategy));

    var current_sortStrategy = (Service.Enums.PostSortStrategy)ViewData["SortStrategy"];
    var current_filterStrategy = (Service.Enums.PostFilterStrategy)ViewData["FilterStrategy"];
    var current_filterData = (string)ViewData["FilterData"];

}

<br />

<div class="container">

    <div class="row">
        <div class="col-md-2">
            <!--Put current author face here-->
        </div>
        <div class="col-md-8">

            <div class="col-md-6" style="padding-left: 0">
                <form method="get" class="form-inline" enctype="multipart/form-data" asp-controller="Posts" asp-action="Index" style="display: inline-block;">
                    <input type="text" class="form-control" id="filterData" name="filterData" placeholder="Search by name..." value="@current_filterData">
                    <input type="hidden" name="postStrategy" id="sortStrategy" value=@current_sortStrategy>
                    <input type="hidden" name="filterStrategy" id="filterStrategy" value="@Service.Enums.PostFilterStrategy.DisplayName">
                    <span class="input-group-btn" style="display: inline-block;">
                        <button class="btn btn-primary" type="submit" style="display: inline-block;">
                            <span class="glyphicon glyphicon-search" aria-hidden="true">
                            </span>
                        </button>
                    </span>
                </form>
            </div>
            <div class="col-md-6" style="padding-right: 0">

                <span class="pull-right" style="display: inline-block;">

                    <!--Date_Descending,
                    Date_Ascending,
                    Likes_Descending,
                    Likes_Ascending,
                    Comments_Descending,
                    Comments_Ascending-->

                    @{


                        string style = "btn btn-info";
                        string glyph = "glyphicon glyphicon-arrow-down";

                        var strategy = Service.Enums.PostSortStrategy.Likes_Descending;

                        if (current_sortStrategy == Service.Enums.PostSortStrategy.Likes_Ascending || current_sortStrategy == Service.Enums.PostSortStrategy.Likes_Descending)
                        {
                            style = "btn btn-primary";

                            if (current_sortStrategy == Service.Enums.PostSortStrategy.Likes_Descending)
                            {
                                glyph = "glyphicon glyphicon-arrow-down";
                                strategy = Service.Enums.PostSortStrategy.Likes_Ascending;
                            }
                            else
                            {
                                glyph = "glyphicon glyphicon-arrow-up";
                                strategy = Service.Enums.PostSortStrategy.Likes_Descending;
                            }

                        }

                        <button type="button" class="@style" onclick="location.href='@Url.Action("Index", "Posts",new {sortStrategy=strategy,filterStrategy=current_filterStrategy,FilterData=current_filterData})'">
                            <span class="glyphicon glyphicon-heart" aria-hidden="true">
                            </span>
                            <span class="@glyph" aria-hidden="true">
                            </span>
                        </button>

                        style = "btn btn-info";
                        glyph = "glyphicon glyphicon-arrow-down";
                        strategy = Service.Enums.PostSortStrategy.Comments_Descending;

                        if (current_sortStrategy == Service.Enums.PostSortStrategy.Comments_Ascending || current_sortStrategy == Service.Enums.PostSortStrategy.Comments_Descending)
                        {
                            style = "btn btn-primary";

                            if (current_sortStrategy == Service.Enums.PostSortStrategy.Comments_Descending)
                            {
                                glyph = "glyphicon glyphicon-arrow-down";
                                strategy = Service.Enums.PostSortStrategy.Comments_Ascending;
                            }
                            else
                            {
                                glyph = "glyphicon glyphicon-arrow-up";
                                strategy = Service.Enums.PostSortStrategy.Comments_Descending;
                            }

                        }

                        <button type="button" class="@style" onclick="location.href='@Url.Action("Index", "Posts",new {sortStrategy=strategy,filterStrategy=current_filterStrategy,filterData=current_filterData})'">
                            <span class="glyphicon glyphicon-comment" aria-hidden="true">
                            </span>
                            <span class="@glyph" aria-hidden="true">
                            </span>
                        </button>

                        style = "btn btn-info";
                        glyph = "glyphicon glyphicon-arrow-down";
                        strategy = Service.Enums.PostSortStrategy.Date_Descending;

                        if (current_sortStrategy == Service.Enums.PostSortStrategy.Date_Ascending || current_sortStrategy == Service.Enums.PostSortStrategy.Date_Descending || current_sortStrategy == Service.Enums.PostSortStrategy.None)
                        {
                            style = "btn btn-primary";

                            if (current_sortStrategy == Service.Enums.PostSortStrategy.Date_Descending || current_sortStrategy == Service.Enums.PostSortStrategy.None)
                            {
                                glyph = "glyphicon glyphicon-arrow-down";
                                strategy = Service.Enums.PostSortStrategy.Date_Ascending;
                            }
                            else
                            {
                                glyph = "glyphicon glyphicon-arrow-up";
                                strategy = Service.Enums.PostSortStrategy.Date_Descending;
                            }

                        }

                        <button type="button" class="@style" onclick="location.href='@Url.Action("Index", "Posts",new {sortStrategy=strategy,filterStrategy=current_filterStrategy,filterData=current_filterData})'">
                            <span class="glyphicon glyphicon-time" aria-hidden="true">
                            </span>
                            <span class="@glyph" aria-hidden="true">
                            </span>
                        </button>
                    }

                </span>
            </div>


        </div>
        <div class="col-md-2">
            <div>

            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">

        </div>
        <div class="col-md-8">
            

            @if (pager.TotalPages > 1)
            {
            <ul class="pagination">
                @if (pager.CurrentPage > 1)
                {
                    <li class="page-item">
                        <a class="page-link" href="@Url.Action("Index", "Posts",new {pg = 1, sortStrategy=current_sortStrategy,filterStrategy=current_filterStrategy,FilterData=current_filterData})">First</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="@Url.Action("Index", "Posts",new {pg = pageNo-1, sortStrategy=current_sortStrategy,filterStrategy=current_filterStrategy,FilterData=current_filterData})">Previous</a>
                    </li>
                }

                @for (var pge = pager.StartPage; pge <= pager.EndPage; pge++)
                {
                    <li class="page-item @(pge == pager.CurrentPage ? "active" : "")">
                        <a class="page-link" href="@Url.Action("Index", "Posts",new {pg = pge, sortStrategy=current_sortStrategy,filterStrategy=current_filterStrategy,FilterData=current_filterData})">@pge</a>
                    </li>
                }

                @if (pager.CurrentPage < pager.TotalPages)
                {
                    <li class="page-item">
                        <a class="page-link" href="@Url.Action("Index", "Posts",new {pg = pageNo+1, sortStrategy=current_sortStrategy,filterStrategy=current_filterStrategy,FilterData=current_filterData})">Next</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="@Url.Action("Index", "Posts",new {pg =pager.TotalPages, sortStrategy=current_sortStrategy,filterStrategy=current_filterStrategy,FilterData=current_filterData})">Last</a>
                    </li>
                }
            </ul>
            }

        </div>
        <div class="col-md-2">

        </div>
    </div>
</div>

<br />

@foreach (var item in Model.PostList)
{
    @Html.Partial("PostSummary", item)
}